### ISSUE TITLE
Bin not working with clear

### ISSUE THREAD

**Issue by larrylawl** [AY1920S1-CS2103-F09-4/main#189]
#### Issue description
Bin not working with clear

#### Steps to reproduce the issue

1.  `clear`
2.  `listbin` 
3. 

#### What's the expected result?

- All my deleted items

#### What's the actual result?

- No items

#### Additional details / screenshot
Think we should remove the command clear? what do you think?

**Comment by ybchen97** [comment]
Changed the definition of clear. Clear is supposed to clear out the entire addressbook, including the bin. Refer to #196
