### ISSUE TITLE
Addtag renders entire list of people instead of current list of people

### ISSUE THREAD

**Issue by larrylawl** [AY1920S1-CS2103-F09-4/main#217]
**Describe the bug**
Addtag always renders entire list of people instead of current list of people

**To Reproduce**
1. `add n/John Doe ic/S9999999J p/98765432 e/johnd@example.com a/John street, block 123, #01-01 dob/12.09.1980 g/Male`
2. `find John`
3. `addtag 1/diabetic`

**Actual behavior**
List of people is shown.

**Expected behavior**
Only John is shown.

**Screenshots**

**Additional context**

**Comment by olivercheok20** [comment]
Thanks Larry! Fixed in latest PR.
